apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db
      name: mongodb
  serviceName: mongodb-svc
  template:
    metadata:
      labels:
        app: db
        name: mongodb
    spec:
      terminationGracePeriodSeconds: 10 
      containers:
      - name: mongo
        image: mongo:4.2.11-bionic
        command:
          - mongod
        args:
          - --bind_ip=0.0.0.0
          - --replSet=rs0
          - --dbpath=/data/db
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: "100m"
            memory: "500Mi"
          requests:
            cpu: "100m"
            memory: "500Mi"
        volumeMounts:
        - name: exercise-vol
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: exercise-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi