apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db
      name: mongodb
  serviceName: mongodb-svc
  template:
    metadata:
      labels:
        app: db
        name: mongodb
    spec:
      terminationGracePeriodSeconds: 10 
      containers:
      - name: mongo
        image: mongo:4.2.11-bionic
        command:
          - mongod
        args:
          - --bind_ip=0.0.0.0
          - --replSet=rs0
          - --dbpath=/data/db
        ports:
        - containerPort: 27017