apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: web
    name: mongo-express
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
      name: mongo-express
  template:
    metadata:
      labels:
        app: web
        name: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:0.54.0
        ports:
          - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongodb://mongo-statefulset-0.mongodb-svc,mongo-statefulset-1.mongodb-svc,mongo-statefulset-2.mongodb-svc?replicaSet=ns0