apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ex-2-nginx-server
  labels: 
    app: nginx-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
        labels:
          app: nginx-server
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.6
        resources:
          limits:
            cpu: "256m"
            memory: "100Mi"
          requests:
            cpu: "256m"
            memory: "100Mi"