apiVersion: v1
kind: Pod
metadata:
  name: ex-1-nginx-server
  labels: 
    app: nginx-server
spec:
  containers:
  - name: nginx
    image: nginx:1.19.6
    resources:
      limits:
        cpu: "256m"
        memory: "100Mi"
      requests:
        cpu: "256m"
        memory: "100Mi"