apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex-5-green
  labels: 
    app: nginx-server
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-server
      version: "1.19.6"
  template:
    metadata:
      labels:
        app: nginx-server
        version: "1.19.6"
    spec:
      containers:
      - image: nginx:1.19.6
        name: nginx
        ports:
            - name: http
              containerPort: 80
        resources:
          limits:
            cpu: "256m"
            memory: "100Mi"
          requests:
            cpu: "256m"
            memory: "100Mi"