apiVersion: v1
kind: Service
metadata: 
  name: green-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector: 
    app: nginx-server
    version: "1.19.6"
  type: NodePort