apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex-4-nginx-server
  labels: 
    app: nginx-server
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
      - image: nginx:1.19.6
        name: nginx